// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzviudmiwhwbiezpcwkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6dml1ZG1pd2h3YmllenBjd2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjQxNTcsImV4cCI6MjA2ODc0MDE1N30.Rz3l4a1QuxGUnLpvDuNeuoWYzGUOhheEv7PF_N8UH0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});